#!/bin/sh

. "${SNAP}/utilities/setup"

exec "${SNAP}/bin/ovn-exporter" \
    -web.listen-address="$(listen_address)" \
    -database.northbound.file.data.path /var/lib/ovn/ovnnb_db.db \
    -database.northbound.file.log.path /var/log/ovn/ovsdb-server-nb.log \
    -database.northbound.file.pid.path /run/ovn/ovnnb_db.pid \
    -database.northbound.socket.control unix:/run/ovn/ovnnb_db.ctl \
    -database.northbound.socket.remote unix:/run/ovn/ovnnb_db.sock \
    -database.southbound.file.data.path /var/lib/ovn/ovnsb_db.db \
    -database.southbound.file.log.path /var/log/ovn/ovsdb-server-sb.log \
    -database.southbound.file.pid.path /run/ovn/ovnsb_db.pid \
    -database.southbound.socket.control unix:/run/ovn/ovnsb_db.ctl \
    -database.southbound.socket.remote unix:/run/ovn/ovnsb_db.sock \
    -service.ovn.northd.file.log.path /var/log/ovn/ovn-northd.log \
    -service.ovn.northd.file.pid.path /run/ovn/ovn-northd.pid \
    -database.vswitch.socket.remote unix:/run/openvswitch/db.sock \
    -database.vswitch.file.pid.path /run/openvswitch/ovsdb-server.pid \
    -service.vswitchd.file.pid.path /run/openvswitch/ovs-vswitchd.pid \
    -system.run.dir /run/openvswitch
